import Head from 'next/head'
import gojuon, { SeionnType } from '@/data/gojuon'

const audioMap: Record<string, HTMLAudioElement> = {};

const GojuonGrid: React.FC<{
  title: string,
  gojuon: SeionnType,
  column?: 5 | 3
}> = ({ title, gojuon, column = 5 }) => {

  const layoutCls = column === 5 ? 'w-1/5' : 'w-1/3';
  const handleClick = (sound?: string) => {
    if (!sound) return;

    if (audioMap[sound]) {
      audioMap[sound].currentTime = 0;
      audioMap[sound].play();
      return;
    } else {
      const audio = new Audio(`${sound}`);
      audioMap[sound] = audio;
      audio.play();
    }
  }

  if (gojuon.length === 0) return null;

  return <>
    <div className='text-center border text-gray-400 leading-8'>{title}</div>
    <div className='flex flex-wrap justify-between items-stretch min-h-screen'>
      {gojuon.map(seionn => (
        <div
          onClick={() => handleClick(seionn.sound)}
          key={seionn.roomaji}
          className={`${layoutCls} flex flex-col justify-around items-center border border-gray-100`}
        >
          {Object.keys(seionn).length > 0 && (
            <>
              <div className='font-sans text-2xl'>{seionn.roomaji}</div>
              <div className='text-sm text-gray-400 font-light'>{seionn.katakana}/{seionn.hiragana}</div>
            </>
          )}
        </div>
      ))}
    </div>
  </>

}

export default function Home() {

  return (
    <>
      <Head>
        <title>五十音图</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>

        <GojuonGrid gojuon={gojuon.seionn} title="清音" />
        <GojuonGrid gojuon={gojuon.dakuonn} title="浊音" />
        <GojuonGrid gojuon={gojuon.youonn} column={3} title="拗音" />

      </main >
    </>
  )
}
